
[theme]
primaryColor = "#d33682"
backgroundColor =  "#ffffff"
secondaryBackgroundColor = "#7c3c7d" #Afeta o sidebar
textColor = "#444444" # afeta todo texto
font = "sans serif"

[server]
fileWatcherType = "none"

