

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#fffdff"
secondaryBackgroundColor = "#DDDDDD"
textColor = "#444444"
font = "sans serif"



# Exemplos visuais rápidos:
# Componente	                Depende de
# Botão (st.button())	        primaryColor
# Sidebar (st.sidebar.*)	    secondaryBackgroundColor
# Fundo da página	            backgroundColor
# Texto padrão	                textColor