

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#f0f8ff"
secondaryBackgroundColor = "#fdfdfd"
textColor = "#444444"
font = "sans serif"



# Exemplos visuais rápidos:
# Componente	                Depende de
# Botão (st.button())	        primaryColor
# Sidebar (st.sidebar.*)	    secondaryBackgroundColor
# Fundo da página	            backgroundColor
# Texto padrão	                textColor