
[theme]
primaryColor = "#d33682"
backgroundColor = "#FBFBFB"
secondaryBackgroundColor = "#fdfdfd"
textColor = "#444444"
font = "sans serif"

[browser]
toolbarMode = "minimal"

[server]
fileWatcherType = "none"
